name: gophermart

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DB
    volumes:
      - ../db/postgres_data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 4

  gophermart:
    build: ..
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_DB: $DB_DB
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    hostname: gophermart
    ports:
      - "8080:8080"
    links:
      - "postgres"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 2
